# Generated by Django 5.1.5 on 2025-04-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='budget_categories',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
