# Generated by Django 5.1.5 on 2025-04-23 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_budget_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='budget_categories',
        ),
    ]
