# Generated by Django 5.1.5 on 2025-04-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_budgetcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcategory',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='budget_limit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
